### ISSUE TITLE
config.yml problem

### ISSUE THREAD

**Issue by niceperl** [burnersk/Dancer2-Logger-Console-Colored#6]
I spent some time trying to activate your logger via `config.yml`:
```
logger: Console::Colored
engines:
    logger:
        Console::Colored:
        ...
```
but it didn't work. I have to write something like this in my code:
`set logger => 'Console::Colored';`

Am I doing something wrong?

**Comment by simbabque** [comment]
You need to set the logger type in the environment. 

    logger: "Console::Colored"

Needs to go into `environments/development.yml`.  Took me a moment to figure that one out, too. I only maintain this, but I hardly ever use Dancer myself any more unfortunately.

My tactic for figuring this out was to look for other Loggers on CPAN with more than one word. [Dancer2::Logger::File::RotateLogs](https://metacpan.org/pod/Dancer2::Logger::File::RotateLogs) has a note about the environment. I'll add one to the documentation here as well. Thanks for pointing it out.

**Comment by simbabque** [comment]
I've released version 0.005, which has a note in the SYNOPSIS. But I forgot to link this issue, so here's the commit: d9b30129d1dc4ff2cf2da3f8d6d28d4a8c768fb8

**Comment by niceperl** [comment]
Thanks.
I am trying to install the new version, but cpanm cannot find the new release:
```
$ cpanm Dancer2::Logger::Console::Colored
Dancer2::Logger::Console::Colored is up to date. (0.004)
```

So, no 0.005 is available at this moment (I think it's enough time since you realese it to CPAN)

**Comment by simbabque** [comment]
That's weird. I get the same thing, but I have no idea why that happens.
But it's only a doc fix anyway. Strange. I've asked about it in #toolchain,
let's see if someone else is smarter than I am. :)

**Comment by niceperl** [comment]
I have just installed the 0.006 release without a problem
Thanks for your great work

**Comment by simbabque** [comment]
Grinnz and Ether helped me figure it out. The version for the .pm file in
the META.json was missing because the dist.ini was set up in a not so great
way. Sorry about that. It should be fixed now, and Ether promised to clean
up my mess.

Enjoy the logger. :)
